name: 'Scan Codeowners'
description: 'Scans changes against codeowners'
author: 'Cory Forsyth'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'input description here'
runs:
  using: 'node16'
  main: 'dist/index.js'
