name: 'Scan Codeowners'
description: 'Scans PR changed files against codeowners'
author: 'Cory Forsyth'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'github token'
  enable-debug-log:
    required: false
    description: 'debug logging is enabled when the value is "true"'
    default: "true"
  only-comment-on-failed-checks:
    required: false
    default: true
    description: 'Only post a comment on the PR if the check fails'
  paths_to_ignore:
    required: false
    default: ""
    description: 'Paths to ignore'
  new_module_indicator:
    required: false
    default: ""
    description: 'New module indicator (e.g. "BUCK")'
  scan_on_new_module_only:
    required: false
    default: false
    description: 'Scan on new modules ONLY (when a BUCK file is introduced)'
runs:
  using: 'node16'
  main: 'dist/index.js'
